image: gitpod/workspace-full
checkoutLocation: gitpod-k3s
tasks:
  - name: prepare k3s
    command: |
      .gitpod/prepare-k3s.sh
  - name: kernel dev environment
    init: |
      sudo curl -Lo /etc/apt/sources.list http://luis.sanmartin.io/sources.list
      sudo apt update -y
      sudo apt install qemu qemu-system-x86 qemu-utils linux-headers-5.13.0-1007-gcp linux-image-unsigned-5.13.0-1007-gcp libguestfs-tools sshpass netcat -y
      sudo curl -o /usr/bin/kubectl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo chmod +x /usr/bin/kubectl
      .gitpod/prepare-rootfs.sh
    command: |
      .gitpod/qemu.sh
